spring.application.name=gestion_inventario
#spring.security.user.name=admin
#spring.security.user.password=admin


## Para levantar proyecto con Docker-compose
spring.datasource.url=jdbc:postgresql://db:5432/inventarios

# Para levantar proyecto sin Docker-compose
#spring.datasource.url=jdbc:postgresql://localhost:5432/inventarios

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info,prometheus
