services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: inventarios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9
    command: >
      -url=jdbc:postgresql://db:5432/inventarios
      -user=postgres
      -password=postgres
      -locations=filesystem:/flyway/sql
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventarios
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      - db
      - flyway

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    expose:
      - "9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  db-data:
